#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDemo.Code
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="allianc_promo")]
	public partial class PuntoVentaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertcustomer(customer instance);
    partial void Updatecustomer(customer instance);
    partial void Deletecustomer(customer instance);
    partial void Insertsystem_user(system_user instance);
    partial void Updatesystem_user(system_user instance);
    partial void Deletesystem_user(system_user instance);
    #endregion
		
		public PuntoVentaDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["allianc_promoConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PuntoVentaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PuntoVentaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PuntoVentaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PuntoVentaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<customer> customers
		{
			get
			{
				return this.GetTable<customer>();
			}
		}
		
		public System.Data.Linq.Table<system_user> system_users
		{
			get
			{
				return this.GetTable<system_user>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.customer")]
	public partial class customer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _customer_id;
		
		private string _customer_type;
		
		private string _specialty_1;
		
		private string _specialty_2;
		
		private string _name_1;
		
		private string _name_2;
		
		private string _name_3;
		
		private string _name_4;
		
		private string _email;
		
		private string _RFC;
		
		private string _license;
		
		private string _status;
		
		private System.Nullable<System.DateTime> _status_change_date;
		
		private System.Nullable<System.DateTime> _creation_date;
		
		private System.Nullable<int> _creator_territory_id;
		
		private System.Nullable<int> _creator_employee_id;
		
		private string _external_id_1;
		
		private string _external_id_2;
		
		private string _external_id_3;
		
		private string _external_id_4;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncustomer_idChanging(int value);
    partial void Oncustomer_idChanged();
    partial void Oncustomer_typeChanging(string value);
    partial void Oncustomer_typeChanged();
    partial void Onspecialty_1Changing(string value);
    partial void Onspecialty_1Changed();
    partial void Onspecialty_2Changing(string value);
    partial void Onspecialty_2Changed();
    partial void Onname_1Changing(string value);
    partial void Onname_1Changed();
    partial void Onname_2Changing(string value);
    partial void Onname_2Changed();
    partial void Onname_3Changing(string value);
    partial void Onname_3Changed();
    partial void Onname_4Changing(string value);
    partial void Onname_4Changed();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnRFCChanging(string value);
    partial void OnRFCChanged();
    partial void OnlicenseChanging(string value);
    partial void OnlicenseChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void Onstatus_change_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onstatus_change_dateChanged();
    partial void Oncreation_dateChanging(System.Nullable<System.DateTime> value);
    partial void Oncreation_dateChanged();
    partial void Oncreator_territory_idChanging(System.Nullable<int> value);
    partial void Oncreator_territory_idChanged();
    partial void Oncreator_employee_idChanging(System.Nullable<int> value);
    partial void Oncreator_employee_idChanged();
    partial void Onexternal_id_1Changing(string value);
    partial void Onexternal_id_1Changed();
    partial void Onexternal_id_2Changing(string value);
    partial void Onexternal_id_2Changed();
    partial void Onexternal_id_3Changing(string value);
    partial void Onexternal_id_3Changed();
    partial void Onexternal_id_4Changing(string value);
    partial void Onexternal_id_4Changed();
    #endregion
		
		public customer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customer_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int customer_id
		{
			get
			{
				return this._customer_id;
			}
			set
			{
				if ((this._customer_id != value))
				{
					this.Oncustomer_idChanging(value);
					this.SendPropertyChanging();
					this._customer_id = value;
					this.SendPropertyChanged("customer_id");
					this.Oncustomer_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_customer_type", DbType="VarChar(4)")]
		public string customer_type
		{
			get
			{
				return this._customer_type;
			}
			set
			{
				if ((this._customer_type != value))
				{
					this.Oncustomer_typeChanging(value);
					this.SendPropertyChanging();
					this._customer_type = value;
					this.SendPropertyChanged("customer_type");
					this.Oncustomer_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_specialty_1", DbType="VarChar(4)")]
		public string specialty_1
		{
			get
			{
				return this._specialty_1;
			}
			set
			{
				if ((this._specialty_1 != value))
				{
					this.Onspecialty_1Changing(value);
					this.SendPropertyChanging();
					this._specialty_1 = value;
					this.SendPropertyChanged("specialty_1");
					this.Onspecialty_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_specialty_2", DbType="VarChar(4)")]
		public string specialty_2
		{
			get
			{
				return this._specialty_2;
			}
			set
			{
				if ((this._specialty_2 != value))
				{
					this.Onspecialty_2Changing(value);
					this.SendPropertyChanging();
					this._specialty_2 = value;
					this.SendPropertyChanged("specialty_2");
					this.Onspecialty_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_1", DbType="VarChar(100)")]
		public string name_1
		{
			get
			{
				return this._name_1;
			}
			set
			{
				if ((this._name_1 != value))
				{
					this.Onname_1Changing(value);
					this.SendPropertyChanging();
					this._name_1 = value;
					this.SendPropertyChanged("name_1");
					this.Onname_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_2", DbType="VarChar(100)")]
		public string name_2
		{
			get
			{
				return this._name_2;
			}
			set
			{
				if ((this._name_2 != value))
				{
					this.Onname_2Changing(value);
					this.SendPropertyChanging();
					this._name_2 = value;
					this.SendPropertyChanged("name_2");
					this.Onname_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_3", DbType="VarChar(100)")]
		public string name_3
		{
			get
			{
				return this._name_3;
			}
			set
			{
				if ((this._name_3 != value))
				{
					this.Onname_3Changing(value);
					this.SendPropertyChanging();
					this._name_3 = value;
					this.SendPropertyChanged("name_3");
					this.Onname_3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_4", DbType="VarChar(100)")]
		public string name_4
		{
			get
			{
				return this._name_4;
			}
			set
			{
				if ((this._name_4 != value))
				{
					this.Onname_4Changing(value);
					this.SendPropertyChanging();
					this._name_4 = value;
					this.SendPropertyChanged("name_4");
					this.Onname_4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(100)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RFC", DbType="VarChar(100)")]
		public string RFC
		{
			get
			{
				return this._RFC;
			}
			set
			{
				if ((this._RFC != value))
				{
					this.OnRFCChanging(value);
					this.SendPropertyChanging();
					this._RFC = value;
					this.SendPropertyChanged("RFC");
					this.OnRFCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_license", DbType="VarChar(100)")]
		public string license
		{
			get
			{
				return this._license;
			}
			set
			{
				if ((this._license != value))
				{
					this.OnlicenseChanging(value);
					this.SendPropertyChanging();
					this._license = value;
					this.SendPropertyChanged("license");
					this.OnlicenseChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(4)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status_change_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> status_change_date
		{
			get
			{
				return this._status_change_date;
			}
			set
			{
				if ((this._status_change_date != value))
				{
					this.Onstatus_change_dateChanging(value);
					this.SendPropertyChanging();
					this._status_change_date = value;
					this.SendPropertyChanged("status_change_date");
					this.Onstatus_change_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creation_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> creation_date
		{
			get
			{
				return this._creation_date;
			}
			set
			{
				if ((this._creation_date != value))
				{
					this.Oncreation_dateChanging(value);
					this.SendPropertyChanging();
					this._creation_date = value;
					this.SendPropertyChanged("creation_date");
					this.Oncreation_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creator_territory_id", DbType="Int")]
		public System.Nullable<int> creator_territory_id
		{
			get
			{
				return this._creator_territory_id;
			}
			set
			{
				if ((this._creator_territory_id != value))
				{
					this.Oncreator_territory_idChanging(value);
					this.SendPropertyChanging();
					this._creator_territory_id = value;
					this.SendPropertyChanged("creator_territory_id");
					this.Oncreator_territory_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creator_employee_id", DbType="Int")]
		public System.Nullable<int> creator_employee_id
		{
			get
			{
				return this._creator_employee_id;
			}
			set
			{
				if ((this._creator_employee_id != value))
				{
					this.Oncreator_employee_idChanging(value);
					this.SendPropertyChanging();
					this._creator_employee_id = value;
					this.SendPropertyChanged("creator_employee_id");
					this.Oncreator_employee_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_external_id_1", DbType="VarChar(100)")]
		public string external_id_1
		{
			get
			{
				return this._external_id_1;
			}
			set
			{
				if ((this._external_id_1 != value))
				{
					this.Onexternal_id_1Changing(value);
					this.SendPropertyChanging();
					this._external_id_1 = value;
					this.SendPropertyChanged("external_id_1");
					this.Onexternal_id_1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_external_id_2", DbType="VarChar(100)")]
		public string external_id_2
		{
			get
			{
				return this._external_id_2;
			}
			set
			{
				if ((this._external_id_2 != value))
				{
					this.Onexternal_id_2Changing(value);
					this.SendPropertyChanging();
					this._external_id_2 = value;
					this.SendPropertyChanged("external_id_2");
					this.Onexternal_id_2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_external_id_3", DbType="VarChar(100)")]
		public string external_id_3
		{
			get
			{
				return this._external_id_3;
			}
			set
			{
				if ((this._external_id_3 != value))
				{
					this.Onexternal_id_3Changing(value);
					this.SendPropertyChanging();
					this._external_id_3 = value;
					this.SendPropertyChanged("external_id_3");
					this.Onexternal_id_3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_external_id_4", DbType="VarChar(100)")]
		public string external_id_4
		{
			get
			{
				return this._external_id_4;
			}
			set
			{
				if ((this._external_id_4 != value))
				{
					this.Onexternal_id_4Changing(value);
					this.SendPropertyChanging();
					this._external_id_4 = value;
					this.SendPropertyChanged("external_id_4");
					this.Onexternal_id_4Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.system_users")]
	public partial class system_user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _system_user_id;
		
		private string _first_name;
		
		private string _first_last_name;
		
		private string _display_label;
		
		private string _login_user_name;
		
		private string _login_user_password;
		
		private string _password_recovery_answer;
		
		private string _password_status;
		
		private System.Nullable<int> _employee_id;
		
		private string _status;
		
		private System.DateTime _creation_date;
		
		private string _qvw_password;
		
		private string _qvw_domain_user;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsystem_user_idChanging(int value);
    partial void Onsystem_user_idChanged();
    partial void Onfirst_nameChanging(string value);
    partial void Onfirst_nameChanged();
    partial void Onfirst_last_nameChanging(string value);
    partial void Onfirst_last_nameChanged();
    partial void Ondisplay_labelChanging(string value);
    partial void Ondisplay_labelChanged();
    partial void Onlogin_user_nameChanging(string value);
    partial void Onlogin_user_nameChanged();
    partial void Onlogin_user_passwordChanging(string value);
    partial void Onlogin_user_passwordChanged();
    partial void Onpassword_recovery_answerChanging(string value);
    partial void Onpassword_recovery_answerChanged();
    partial void Onpassword_statusChanging(string value);
    partial void Onpassword_statusChanged();
    partial void Onemployee_idChanging(System.Nullable<int> value);
    partial void Onemployee_idChanged();
    partial void OnstatusChanging(string value);
    partial void OnstatusChanged();
    partial void Oncreation_dateChanging(System.DateTime value);
    partial void Oncreation_dateChanged();
    partial void Onqvw_passwordChanging(string value);
    partial void Onqvw_passwordChanged();
    partial void Onqvw_domain_userChanging(string value);
    partial void Onqvw_domain_userChanged();
    #endregion
		
		public system_user()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_system_user_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int system_user_id
		{
			get
			{
				return this._system_user_id;
			}
			set
			{
				if ((this._system_user_id != value))
				{
					this.Onsystem_user_idChanging(value);
					this.SendPropertyChanging();
					this._system_user_id = value;
					this.SendPropertyChanged("system_user_id");
					this.Onsystem_user_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_first_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string first_name
		{
			get
			{
				return this._first_name;
			}
			set
			{
				if ((this._first_name != value))
				{
					this.Onfirst_nameChanging(value);
					this.SendPropertyChanging();
					this._first_name = value;
					this.SendPropertyChanged("first_name");
					this.Onfirst_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_first_last_name", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string first_last_name
		{
			get
			{
				return this._first_last_name;
			}
			set
			{
				if ((this._first_last_name != value))
				{
					this.Onfirst_last_nameChanging(value);
					this.SendPropertyChanging();
					this._first_last_name = value;
					this.SendPropertyChanged("first_last_name");
					this.Onfirst_last_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_display_label", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string display_label
		{
			get
			{
				return this._display_label;
			}
			set
			{
				if ((this._display_label != value))
				{
					this.Ondisplay_labelChanging(value);
					this.SendPropertyChanging();
					this._display_label = value;
					this.SendPropertyChanged("display_label");
					this.Ondisplay_labelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_login_user_name", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string login_user_name
		{
			get
			{
				return this._login_user_name;
			}
			set
			{
				if ((this._login_user_name != value))
				{
					this.Onlogin_user_nameChanging(value);
					this.SendPropertyChanging();
					this._login_user_name = value;
					this.SendPropertyChanged("login_user_name");
					this.Onlogin_user_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_login_user_password", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string login_user_password
		{
			get
			{
				return this._login_user_password;
			}
			set
			{
				if ((this._login_user_password != value))
				{
					this.Onlogin_user_passwordChanging(value);
					this.SendPropertyChanging();
					this._login_user_password = value;
					this.SendPropertyChanged("login_user_password");
					this.Onlogin_user_passwordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password_recovery_answer", DbType="VarChar(100)")]
		public string password_recovery_answer
		{
			get
			{
				return this._password_recovery_answer;
			}
			set
			{
				if ((this._password_recovery_answer != value))
				{
					this.Onpassword_recovery_answerChanging(value);
					this.SendPropertyChanging();
					this._password_recovery_answer = value;
					this.SendPropertyChanged("password_recovery_answer");
					this.Onpassword_recovery_answerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password_status", DbType="VarChar(4)")]
		public string password_status
		{
			get
			{
				return this._password_status;
			}
			set
			{
				if ((this._password_status != value))
				{
					this.Onpassword_statusChanging(value);
					this.SendPropertyChanging();
					this._password_status = value;
					this.SendPropertyChanged("password_status");
					this.Onpassword_statusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employee_id", DbType="Int")]
		public System.Nullable<int> employee_id
		{
			get
			{
				return this._employee_id;
			}
			set
			{
				if ((this._employee_id != value))
				{
					this.Onemployee_idChanging(value);
					this.SendPropertyChanging();
					this._employee_id = value;
					this.SendPropertyChanged("employee_id");
					this.Onemployee_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_status", DbType="VarChar(4)")]
		public string status
		{
			get
			{
				return this._status;
			}
			set
			{
				if ((this._status != value))
				{
					this.OnstatusChanging(value);
					this.SendPropertyChanging();
					this._status = value;
					this.SendPropertyChanged("status");
					this.OnstatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_creation_date", DbType="DateTime NOT NULL")]
		public System.DateTime creation_date
		{
			get
			{
				return this._creation_date;
			}
			set
			{
				if ((this._creation_date != value))
				{
					this.Oncreation_dateChanging(value);
					this.SendPropertyChanging();
					this._creation_date = value;
					this.SendPropertyChanged("creation_date");
					this.Oncreation_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qvw_password", DbType="VarChar(10)")]
		public string qvw_password
		{
			get
			{
				return this._qvw_password;
			}
			set
			{
				if ((this._qvw_password != value))
				{
					this.Onqvw_passwordChanging(value);
					this.SendPropertyChanging();
					this._qvw_password = value;
					this.SendPropertyChanged("qvw_password");
					this.Onqvw_passwordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_qvw_domain_user", DbType="VarChar(50)")]
		public string qvw_domain_user
		{
			get
			{
				return this._qvw_domain_user;
			}
			set
			{
				if ((this._qvw_domain_user != value))
				{
					this.Onqvw_domain_userChanging(value);
					this.SendPropertyChanging();
					this._qvw_domain_user = value;
					this.SendPropertyChanged("qvw_domain_user");
					this.Onqvw_domain_userChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
